- hosts: aws
  become: true

  tasks:
  
    - name: Install firewalld
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Open web ports in firewalld
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ ports }}"

    - name: Check companyplus directory
      block:
 
        - name: Check if directory exists
          stat:
            path: /var/www/html/www.companyplus.com
          register: companyplus_dir
 
        - name: Directory exists
          debug:
            msg: "/var/www/html/www.companyplus.com exists"
          when: companyplus_dir.stat.exists
 
        - name: Directory does not exist
          debug:
            msg: "ERROR: /var/www/html/www.companyplus.com does not exist"
          when: not companyplus_dir.stat.exists

  roles:
    - role: webserver
      vars:
        app_root: html_demo_site-main
        server_name: "{{ ansible_default_ipv4.address }}"
        document_root: /var/www/html
